### ISSUE TITLE
Figure out -SNAPSHOT for this project

### ISSUE THREAD

**Issue by allenhsieh** [sonatype-nexus-community/nexus-repository-apk#2]
FWIW, I'd like to encourage we start using a "-SNAPSHOT" suffix on the version numbers. (I've updated the nexus-format-archetype to do this).
The ORB we use for releasing will handle versions like 0.0.1-SNAPSHOT. One downside is you have to remember to manually bump the version to the next development SNAPSHOT after doing a release.

_Originally posted by @bhamail in https://github.com/sonatype-nexus-community/nexus-repository-apk/pull/1_

**Comment by bhamail** [comment]
Fixed by commit: 5c14ccd5e26bfaf354bb29a7b07d883790f27c2c
