### ISSUE TITLE
Request to upload pre-compiled files to GitHub releases

### ISSUE THREAD

**Issue by LinuxSuRen** [sonatype-nexus-community/nexus-repository-apk#20]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
It'll take a long time to download dependencies and compiles the source code. It's good to upload the pre-compiled files to GitHub release.

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

cc @DarthHater @bhamail

**Comment by bhamail** [comment]
Thanks filing this issue. The pre-compiled files are available on maven central via the badge below. Just click that badge, and you should see them.

![Screen Shot 2020-05-12 at 10 24 41 AM](https://user-images.githubusercontent.com/578919/81703673-e6d5b280-943a-11ea-9851-f2974f608069.png)

**Comment by LinuxSuRen** [comment]
Of course, all maven projects can be uploaded to a Nexus sever. I just forget it before. But it'll be great if we can let it becomes clear.

**Comment by bhamail** [comment]
Makes sense. Please feel free to submit a PR with changes to the README.md that would help make this clearer. I can totally understand how someone would feel like they had to build it all from source.
